#!/bin/ksh
export LC_ALL=en_US
# Generated by MIP v5.7-026
PROMPT_TARG="F"
MIPPATH="/tmp/questa_sim-2019.1.aol"
export MG_INSTALL_PID=`uname -n`-`date +%H.%M.%S`
MIP_PATH_ERRORS=0
MIP_START_DIR=/tmp/mgc/$(basename $MIPPATH)
NEWTARG=
NEWSRC=
NEWMIPLOC=
SELF=$(
SELF=$0
case $0 in
(*/*) ;; (*)
[ -e "$SELF" ] || SELF=$(command -v -- "$SELF") || exit
esac
cd -P -- "$(dirname -- "$SELF")" && pwd -P || exit
) || exit
SELF=$SELF/$(basename $0)
while [ $# -gt 0 ];
do
   if [ "$1" = "-tgt" ]; then
      shift
      NEWTARG=`echo -tgt \'"$1"\'` 
      PROMPT_TARG=F
   elif [ "$1" = "-src" ]; then
      shift
      NEWSRC=`echo -src \'"$1"\'` 
   elif [ "$1" = "-msiloc" ]; then
      shift
      NEWMIPLOC=`echo -msiloc "$1"` 
      MIP_START_DIR="$1"
   else
      echo "USAGE: $0 [-tgt <target>] [-src <source>] [-msiloc <path>]"
      exit 1
   fi
   shift
done
while [ ! -f "$MIPPATH" ];
do
	if [ "$MIPPATH" = "x" ]; then
		exit
	fi
	MIP_PATH_ERRORS=$((MIP_PATH_ERRORS + 1))
	if [ "$MIP_PATH_ERRORS" -gt 9 ]; then
		exit 1
	 fi
	echo "Could not find MIPPATH of: '$MIPPATH'"
	echo "Enter path to install.* (or 'x' to quit): "
	read MIPPATH
done
if [ "$PROMPT_TARG" = "T" ]; then
   echo "Enter a Target Directory: "
   read ENTERED_TARG
   ENTERED_TARG=`echo $ENTERED_TARG | sed 's/"//g'`
   NEWTARG=`echo -tgt \'"$ENTERED_TARG"\'` 
fi
# *** ADD YOUR OWN PRE INSTALL COMMANDS BELOW HERE ***


# *** ADD YOUR OWN PRE INSTALL COMMANDS ABOVE HERE ***
"$MIPPATH" -silent -batch "$SELF" $NEWTARG $NEWSRC $NEWMIPLOC <<!!
d
yes
!!
INSTALLEXIT=$?
#
#
# *** ADD YOUR OWN POST INSTALL COMMANDS BELOW HERE ***


# *** ADD YOUR OWN POST INSTALL COMMANDS ABOVE HERE ***
LASTEXIT=$?
if [ $INSTALLEXIT -ne 0 ]; then
   exit $INSTALLEXIT
fi
exit $LASTEXIT

##### BELOW HERE IS XML DATA #####

<batchFile>
	<source value="/tmp/questa_sim-2019.1.aol"/>
	<target value="/opt/mentor/questa/2019.1"/>
	<installType value="all"/>
	<platform value="Linux"/>
	<release name="2019.1">
		<product name="Questa SIM 64-bit" productroot=""/>
		<product name="GCC 64-bit" productroot=""/>
	</release>
</batchFile>
