= Questa Docker Container Example
// Settings
:doctype: book
:chapter-label:
:idprefix:
:idseparator: -
:sectanchors:
:sectnums:
:sectnumlevels: 4
:toclevels: 4
:source-highlighter: pygments
:toc: left
:icons: font
:imagesdir: images
:xrefstyle: full
:title-page:
:stem:

== Build

[source,sh]
.Build Image
----
docker build --build-arg USER=$USER --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t questa .
----

Build args:

* `USER` - Sets the username for the container.
Set per license server requirements.
* `UID` - The host user ID.
Used to sync the uid of the host and container.
* `GID` - The host group ID.
Used to sync the gid of the host and container.

== Run

[source,sh]
.Run
----
docker run -it -v $PWD:/src -w /src -u $(id -u):$(id -g) -e MGLS_LICENSE_FILE --hostname $HOSTNAME --dns-search $DOMAIN questa <command>
----

Options:

* `-it` - Run interactively
* `-v $PWD:/src` - Mount the host $PWD inside the container at /src
* `-w /src` - Set the container working directory to /src
* `-u $(id -u):$(id -g)` - Set the container uid/gid to that of the host uid/gid.
Necessary for witing files with proper file ownership from the container to the shared volume.
* `-e MGLS_LICENSE_FILE` - Pass the `MGLS_LICENSE_FILE` environment variable into the container.
This environment variable defines the license servers for Questa.
* `--hostname $HOSTNAME` - Set the hostname of the container.
Set per license server requirements.
* `--dns-search $DOMAIN` - Allows the license servers and other non-FQDN to be found on the domain (e.g. example.com).

Parameters:

* `<command>` - The shell command to run inside the container.

Example:

[source,sh]
.Run example
----
docker run -it -v $PWD:/src -w /src -u $(id -u):$(id -g) -e MGLS_LICENSE_FILE --hostname $HOSTNAME --dns-search $DOMAIN questa make
----

[listing]
.Example output
----
vlog -incr hello_world.v
QuestaSim-64 vlog 2020.4_2 Compiler 2020.12 Dec  5 2020
Start time: 08:52:39 on Mar 12,2021
vlog -incr hello_world.v
-- Skipping module hello_world

Top level modules:
        hello_world
End time: 08:52:39 on Mar 12,2021, Elapsed time: 0:00:00
Errors: 0, Warnings: 0
vopt hello_world -o optimized
QuestaSim-64 vopt 2020.4_2 Compiler 2020.12 Dec  5 2020
Start time: 08:52:39 on Mar 12,2021
vopt hello_world -o optimized

Top level modules:
        hello_world

Analyzing design...
-- Loading module hello_world
Incremental compilation check found no design-units have changed.
Optimized design name is optimized
End time: 08:52:39 on Mar 12,2021, Elapsed time: 0:00:00
Errors: 0, Warnings: 0
vsim -batch -do 'run; exit;' optimized
** Warning: setting ADDR_NO_RANDOMIZE failed - Operation not permitted.
# vsim -batch -do "run; exit;" optimized
# Start time: 08:52:39 on Mar 12,2021
# //  Questa Sim-64
# //  Version 2020.4_2 linux_x86_64 Dec  5 2020
# //
# //  Copyright 1991-2020 Mentor Graphics Corporation
# //  All Rights Reserved.
# //
# //  QuestaSim and its associated documentation contain trade
# //  secrets and commercial or financial information that are the property of
# //  Mentor Graphics Corporation and are privileged, confidential,
# //  and exempt from disclosure under the Freedom of Information Act,
# //  5 U.S.C. Section 552. Furthermore, this information
# //  is prohibited from disclosure under the Trade Secrets Act,
# //  18 U.S.C. Section 1905.
# //
# Loading work.hello_world(fast)
#
# run
# hello world
# exit
# End time: 08:52:39 on Mar 12,2021, Elapsed time: 0:00:00
# Errors: 0, Warnings: 0
----

== Docker Compose

A Docker Compose file is also provided to simplify the above.

[source,sh]
----
export MGLS_LICENSE_FILE=...
USER=$USER HOSTNAME=$HOSTNAME DOMAIN=$DOMAIN UID=$(id -u) GID=$(id -g) docker-compose run questa make
----

Modify the `MGLS_LICENSE_FILE`, `USER`, `HOSTNAME`, and `DOMAIN` environment variables as needed.
