= Docker Images for Questa
// Settings
:doctype: book
:chapter-label:
:idprefix:
:idseparator: -
:sectanchors:
:sectnums:
:sectnumlevels: 4
:toclevels: 4
:source-highlighter: pygments
:toc: left
:icons: font
:imagesdir: images
:xrefstyle: full
:title-page:
:stem:

This repository provides Docker images for Questa.

These images were created for running UVM testbenches via a continuous integration service with a FLEXnet license server.

== Usage

. Build the base image
. Push to registry
. Copy the example Dockerfile template into user testbench
. Setup continuous integration service to use user Dockerfile

== Example

=== Build

[source,sh]
.Build Image
----
docker build --build-arg DOCKER_USER=$username --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t questa .
----

Build args:

* `DOCKER_USER` - Sets the username for the container.
Set per license server requirements.
* `UID` - The host user ID.
Used to sync the uid of the host and container.
* `GID` - The host group ID.
Used to sync the gid of the host and container.

=== Run

[source,sh]
.Run
----
docker run -it -v $PWD:/src -w /src -u $(id -u):$(id -g) -e MGLS_LICENSE_FILE --hostname $hostname --dns-search $domain questa <command>
----

Options:

* `-it` - Run interactively
* `-v $PWD:/src` - Mount the host $PWD inside the container at /src
* `-w /src` - Set the container working directory to /src
* `-u $(id -u):$(id -g)` - Set the container uid/gid to that of the host uid/gid.
Necessary for witing files with proper file ownership from the container to the shared volume.
* `-e MGLS_LICENSE_FILE` - Pass the `MGLS_LICENSE_FILE` environment variable into the container.
This environment variable defines the license servers for Questa.
* `--hostname $hostname` - Set the hostname of the container.
Set per license server requirements.
* `--dns-search $domain` - Allows the license servers and other non-FQDN to be found on the domain (e.g. example.com).

Parameters:

* `<command>` - The shell command to run inside the container.

Example:

[source,sh]
.Run example
----
docker run -it -v $PWD:/shared -w /shared -u $(id -u):$(id -g) -e MGLS_LICENSE_FILE --hostname $(hostname) --dns-search $domain questa make
----

[listing]
.Example output
----
vlog -incr hello_world.v
QuestaSim-64 vlog 2020.4_2 Compiler 2020.12 Dec  5 2020
Start time: 08:52:39 on Mar 12,2021
vlog -incr hello_world.v
-- Skipping module hello_world

Top level modules:
        hello_world
End time: 08:52:39 on Mar 12,2021, Elapsed time: 0:00:00
Errors: 0, Warnings: 0
vopt hello_world -o optimized
QuestaSim-64 vopt 2020.4_2 Compiler 2020.12 Dec  5 2020
Start time: 08:52:39 on Mar 12,2021
vopt hello_world -o optimized

Top level modules:
        hello_world

Analyzing design...
-- Loading module hello_world
Incremental compilation check found no design-units have changed.
Optimized design name is optimized
End time: 08:52:39 on Mar 12,2021, Elapsed time: 0:00:00
Errors: 0, Warnings: 0
vsim -batch -do 'run; exit;' optimized
** Warning: setting ADDR_NO_RANDOMIZE failed - Operation not permitted.
# vsim -batch -do "run; exit;" optimized
# Start time: 08:52:39 on Mar 12,2021
# //  Questa Sim-64
# //  Version 2020.4_2 linux_x86_64 Dec  5 2020
# //
# //  Copyright 1991-2020 Mentor Graphics Corporation
# //  All Rights Reserved.
# //
# //  QuestaSim and its associated documentation contain trade
# //  secrets and commercial or financial information that are the property of
# //  Mentor Graphics Corporation and are privileged, confidential,
# //  and exempt from disclosure under the Freedom of Information Act,
# //  5 U.S.C. Section 552. Furthermore, this information
# //  is prohibited from disclosure under the Trade Secrets Act,
# //  18 U.S.C. Section 1905.
# //
# Loading work.hello_world(fast)
#
# run
# hello world
# exit
# End time: 08:52:39 on Mar 12,2021, Elapsed time: 0:00:00
# Errors: 0, Warnings: 0
----

== Notes on Packaging

=== Questa

Questa is large but can be pruned.
Both the Questa GCC and the system GCC must be installed.
The system GCC is required for DPI compilation (e.g. UVM).
Questa GCC is required for Questa VIP.
It may be possible to use just one but I haven't dug any deeper.

Install:

* System GCC
* Questa 64-bit
* Questa provided GCC 64-bit

Do not install:

* Questa 32-bit
* Questa provided GCC 32-bit

Prune:

* The Questa provided GCC installs several versions.
Remove all but the latest GCC from `$QUESTA_ROOT`.
* AVM, OVM, and old versions of UVM may be pruned.
See https://github.com/rfdonnelly/docker-questa/blob/68c9f73136aa959ef42273f03ccf30718bd1c491/2019.1/base/prune-install.sh[prune-install.sh].
But note, these must also be removed from `modelsim.ini`.
See https://github.com/rfdonnelly/docker-questa/blob/68c9f73136aa959ef42273f03ccf30718bd1c491/2019.1/base/prune-install.sh#L61[prune-install.sh:61].

Additional savings may be had by using a smaller base image (e.g. https://hub.docker.com/_/alpine[Alpine]).

=== Questa VIP

The Questa VIP install includes all available Questa VIP.
When packaging, only the VIP used should be packaged.
The QVIP has common components and protocol specific components.
Package all common components but only include the protocol components needed.

Exclude:

* 32-bit components
* Versions compiled with older GCCs

Common components:

* `include/`
* `linux_x86_64/`
* `questa_mvc_core/include/`
* `questa_mvc_core/lib/`
* `questa_mvc_core/linux_x86_64_gcc-7.4.0/libquesta*`
* `questa_mvc_src/sv/mvc_*`

Protocol components:

* `questa_mvc_core/linux_x86_64_gcc-7.4.0/lib<protocol>*`
* `questa_mvc_src/sv/<protocol>`

See the `contrib/package-qvip` script for automating this.
