#!/bin/sh

mkdir shared
cp example/hello_world.v shared/hello_world.v

./docker-run vlog hello_world.v 
./docker-run vopt hello_world -o hello_world_opt
./docker-run vsim -batch -do 'run' -do 'exit' hello_world_opt
