#!/bin/ksh
export LC_ALL=en_US
# *************************************************************************************** 
# *** This file is provided as-is.  Modifications to this file are at your own risk.  *** 
# *** The End User License Agreement was accepted during the creation of this script  *** 
# *** by the user: vagrant                                                               
# *************************************************************************************** 
# Generated by MIP v5.5-015
PROMPT_TARG="F"
MIPPATH="/tmp/install.linux64"
export MG_INSTALL_PID=`uname -n`-`date +%H.%M.%S`
if [ "$HOME" = "" ]; then
   echo  HOME env variable is not set. Please set it to your home directory.
   exit 1
fi
if [[ ! -d "$HOME"  ]]; then
   echo HOME does not resolve to a valid directory.
   exit 1
fi
MIP_PATH_ERRORS=0
MIP_START_DIR=$HOME/mgc/$(basename $MIPPATH)
NEWTARG=
NEWSRC=
NEWMIPLOC=
SELF=$(
SELF=$0
case $0 in
(*/*) ;; (*)
[ -e "$SELF" ] || SELF=$(command -v -- "$SELF") || exit
esac
cd -P -- "$(dirname -- "$SELF")" && pwd -P || exit
) || exit
SELF=$SELF/$(basename $0)
while [ $# -gt 0 ];
do
   if [ "$1" = "-tgt" ]; then
      shift
      NEWTARG=`echo -tgt \'"$1"\'` 
      PROMPT_TARG=F
   elif [ "$1" = "-src" ]; then
      shift
      NEWSRC=`echo -src \'"$1"\'` 
   elif [ "$1" = "-msiloc" ]; then
      shift
      NEWMIPLOC=`echo -msiloc "$1"` 
      MIP_START_DIR="$1"
   else
      echo "USAGE: $0 [-tgt <target>] [-src <source>] [-msiloc <path>]"
      exit 1
   fi
   shift
done
while [ ! -f "$MIPPATH" ];
do
	if [ "$MIPPATH" = "x" ]; then
		exit
	fi
	MIP_PATH_ERRORS=$((MIP_PATH_ERRORS + 1))
	if [ "$MIP_PATH_ERRORS" -gt 9 ]; then
		exit 1
	 fi
	echo "Could not find MIPPATH of: '$MIPPATH'"
	echo "Enter path to install.* (or 'x' to quit): "
	read MIPPATH
done
if [ "$PROMPT_TARG" = "T" ]; then
   echo "Enter a Target Directory: "
   read ENTERED_TARG
   ENTERED_TARG=`echo $ENTERED_TARG | sed 's/"//g'`
   NEWTARG=`echo -tgt \'"$ENTERED_TARG"\'` 
fi
# *** ADD YOUR OWN PRE INSTALL COMMANDS BELOW HERE ***


# *** ADD YOUR OWN PRE INSTALL COMMANDS ABOVE HERE ***
"$MIPPATH" -silent -batch "$SELF" $NEWTARG $NEWSRC $NEWMIPLOC <<!!
d
yes
!!
INSTALLEXIT=$?
#
#
# *** ADD YOUR OWN POST INSTALL COMMANDS BELOW HERE ***


# *** ADD YOUR OWN POST INSTALL COMMANDS ABOVE HERE ***
LASTEXIT=$?
if [ $INSTALLEXIT -ne 0 ]; then
   exit $INSTALLEXIT
fi
exit $LASTEXIT

##### BELOW HERE IS XML DATA #####

<batchFile>
	<source value="/tmp"/>
	<target value="/opt/mentor/questa/10.5c"/>
	<installType value="all"/>
	<platform value="Linux"/>
	<release name="10.5c">
		<product name="questa_sim-base" productroot=""/>
		<product name="questa_sim-docs" productroot=""/>
		<product name="questa_sim-gcc-linux_x86_64" productroot=""/>
		<product name="questa_sim-linux_x86_64" productroot=""/>
	</release>
	<release name="RUVM 4.6">
		<product name="Register Assistant UVM" productroot=""/>
	</release>
</batchFile>
